import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfReader;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Text;

public class ThirdLab {

    public static void main(String[] args) throws Exception {

        PdfFont font = PdfFontFactory.createFont("Shrift.ttf", "CP1251", true);
        PdfWriter writer = new PdfWriter("res.pdf");
        PdfReader reader = new PdfReader("Shablon.pdf");
        PdfDocument pdf = new PdfDocument(reader, writer);
        Document document = new Document(pdf);
        document.setFont(font);
        Paragraph p = new Paragraph(new Text("БАНК НАКОПБАНК"));
        p.setFixedPosition(35, 786, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("23712345"));
        p.setFixedPosition(55, 750, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("791412367"));
        p.setFixedPosition(198, 750, 100);
        p.setFontSize(10);
        document.add(p);
        String whoget = "Жарков Алексей Сергеевич";
        p = new Paragraph(new Text(whoget));
        p.setFixedPosition(35, 737, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("351322"));
        p.setFixedPosition(353, 786, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("6"));
        p.setFixedPosition(353, 775, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("9"));
        p.setFixedPosition(353, 749, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("20 марта"));
        p.setFixedPosition(192, (float) 681.7, 100);
        p.setFontSize(13);
        document.add(p);
        p = new Paragraph(new Text("19"));
        p.setFixedPosition((float) 250.4, (float) 681.7, 100);
        p.setFontSize(13);
        document.add(p);
        p = new Paragraph(new Text("1"));
        p.setFixedPosition(162, 681, 1000);
        p.setFontSize(14);
        document.add(p);
        p = new Paragraph(new Text(whoget));
        p.setFixedPosition(100, 638, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("Федоров Федор Федорович"));
        p.setFixedPosition(100, 605, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("№ 13 от 03.03.1989"));
        p.setFixedPosition(100, 580, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("Интернет и телефония"));
        p.setFixedPosition(65, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        p = new Paragraph(new Text("1"));
        p.setFixedPosition(355, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        p = new Paragraph(new Text("1"));
        p.setFixedPosition(322, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        double price = 751.49; 
        p = new Paragraph(new Text(String.valueOf(price)));
        p.setFixedPosition(390, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        p = new Paragraph(new Text(String.valueOf(price)));
        p.setFixedPosition(457, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        p = new Paragraph(new Text(price + " руб."));
        p.setFixedPosition(450, 491, 1000);
        p.setFontSize(9);
        document.add(p);
        p = new Paragraph(new Text("125.25 руб."));
        p.setFixedPosition(450, 479, 1000);
        p.setFontSize(9);
        document.add(p);
        p = new Paragraph(new Text(price + " руб."));
        p.setFixedPosition(450, 466, 1000);
        p.setFontSize(9);
        document.add(p);
        p = new Paragraph(new Text("Михалков А. С."));
        p.setFixedPosition(451, 334, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("Михалкова О. А."));
        p.setFixedPosition(237, 334, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("1 на сумму " + price + " руб."));
        p.setFixedPosition(122, 451, 1000);
        p.setFontSize(9);
        document.add(p);
        document.close();
    }
}
